# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="kotlinfml"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[1,)"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/williambl/haema/issues"



# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]

# The modid of the mod
modId="haema"

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}"

 # A display name for the mod
displayName="Haema"

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://raw.githubusercontent.com/williambl/haema/master/update.json"

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://github.com/williambl/haema"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile=""

# A text field displayed in the mod UI
credits=""

# A text field displayed in the mod UI
authors="Willbl3pic"

# The description text for the mod (multi line!)
description='''
'''



# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.essentialfeatures]]
    # the modid of the dependency
    modId="forge"
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true
    # The version range of the dependency
    versionRange="[28.1,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.essentialfeatures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"